# Generated by Django 3.0.10 on 2020-09-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waateaapp', '0004_auto_20200909_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='availbility',
            name='selection',
            field=models.IntegerField(choices=[(0, "Not Selected"), (1, "Selected")], default=0),
        ),
    ]
